version: "3"

volumes:
  database:
    driver: local

services:
  db:
    image: postgres:latest
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql-docker/data
  minio-server:
    image: minio/minio
    restart: always
    volumes:
      - ./storage/s3/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${AWS_S3_SECRET_KEY}
    command: server --console-address :9001 /data
  # service not necessary, used here to explain how to interact from the container
  minio-client:
    image: minio/mc
    # insure that the server container is running before building the client
    depends_on:
      - minio-server
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config;
      /usr/bin/mc config host add myminio http://minio-server:9000 ${AWS_S3_ACCESS_KEY} ${AWS_S3_SECRET_KEY};
      /usr/bin/mc mb myminio/test-bucket;
      echo 'my content' > myfile.txt;
      /usr/bin/mc cp myfile.txt myminio/test-bucket;
      exit 0;
      "
