name: Build check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Run build checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install project
        uses: oven-sh/setup-bun@v1
        with:
          version: latest
          run: bun install
      - name: Run typechecks
        uses: oven-sh/setup-bun@v1
        with:
          version: latest
          run: bun run typecheck
      - name: Run build
        uses: oven-sh/setup-bun@v1
        with:
          version: latest
          run: bun run build