name: Build check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Run build checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install project
        run: bun install

      - name: Run typechecks
        run: bun run typecheck
        
      - name: Run build
        run: bun run build